### ISSUE TITLE
*MEDICINE* - long acting opioids

### ISSUE THREAD

**Issue by richiecroker** [opensafely/codelist-development#236]
I have created codelists from the OpenPrescribing measure definitions for both high and "non-high" strength long-acting opioids.  The denominator is the full list minus the high dose ones, as defined in the relevant codelist:

High dose: https://www.opencodelists.org/codelist/user/richard-croker/high-dose-long-acting-opioids-openprescribing/5c42deb7/
Non-high dose: https://www.opencodelists.org/codelist/user/richard-croker/non-high-dose-long-acting-opioids-openprescribing/44b769a3/

**Comment by chrisjwood16** [comment]
@richiecroker re High dose opioid list.
Was difficult to fully review in existing form so I've created a new list for comparison. There are a few differences:
https://www.opencodelists.org/codelist/user/richard-croker/high-dose-long-acting-opioids-openprescribing/5c42deb7/diff/1d638311/

MXL appears to be a 24-hour rather than 12 hour release. https://www.medicines.org.uk/emc/product/1016/smpc#gref
So should only include MXL 120mg, 150mg, 200mg
Onexila XL - similar to above - XL licensed for once a day dosing. So would restrict to only 80mg strength.
Tapentadol - potency is given as 0.4. I would make tapentadol MR 150mg BD equivalent to 120mg OME - so would include tapentadol MR 150mg preps.
Hydromorphone - not much use but 16mg MR and 24 MR given twice a day would exceed 120mg OME

Happy to discuss.

Is it worth also mentioning somewhere that heroin substitutes are excluded (based on conversions some of the once daily sublingual buprenorphine would be >120mg OME)?

**Comment by richiecroker** [comment]
Thanks @chrisjwood16 - apologies, the link above is the old version including MXL - i'd already removed the 60mg and 90mg
Latest version: https://www.opencodelists.org/codelist/user/richard-croker/high-dose-long-acting-opioids-openprescribing/3f51e9b7/

**Comment by richiecroker** [comment]
@chrisjwood16 have created new version, which appears the same as your review:
https://www.opencodelists.org/codelist/user/richard-croker/high-dose-long-acting-opioids-openprescribing/22c902fd/diff/1d638311/
https://www.opencodelists.org/codelist/user/richard-croker/high-dose-long-acting-opioids-openprescribing/22c902fd/diff/1d638311/

**Comment by richiecroker** [comment]
@chrisjwood16 have also amended "non-high" opioids:
https://www.opencodelists.org/codelist/user/richard-croker/non-high-dose-long-acting-opioids-openprescribing/70aa1c92/

And the diff suggests there's no commonality between two codelists (which is correct)
https://www.opencodelists.org/codelist/user/richard-croker/high-dose-long-acting-opioids-openprescribing/22c902fd/diff/70aa1c92/

**Comment by chrisjwood16** [comment]
@richiecroker non-high dose, long acting opiates.
See diff:
https://www.opencodelists.org/codelist/user/richard-croker/non-high-dose-long-acting-opioids-openprescribing/44b769a3/diff/09b98fc8/

- [ ] Buprenorphine 15micrograms/hour inc brands missing
- [ ] Hydromorphone MR 2mg, 4mg and 8mg missing (as above)
- [ ] Onexila XL 40mg missing (as above)
- [ ] Tapentadol MR 25mg inc brands missing
- [ ] Remove tapentadol MR 150mg (as above (120mg OME))

To consider:
Dihydrocodeine modified release and tramadol modified release haven't been included but I would say do fit the description of 
non-high dose, long acting opioids. As 'weak' opioids, they might be more likely to be used for acute courses, but doses convert to higher OME than a number of other opioids included already and for example, DHC CONTINUS is licensed for severe chronic pain.

**Comment by richiecroker** [comment]
@chrisjwood16 latest diff version here:
https://www.opencodelists.org/codelist/user/richard-croker/non-high-dose-long-acting-opioids-openprescribing/0013e8c8/diff/579aa95d/

Main differences:
I've not added anything above presentation level
DF118 is not long acting (tds) AND discontinued...
Added generically rxed DHC continus

**Comment by chrisjwood16** [comment]
Thanks @richiecroker
Happy to approve these final codelists:
High dose: https://www.opencodelists.org/codelist/user/richard-croker/high-dose-long-acting-opioids-openprescribing/22c902fd
Non-high dose: https://www.opencodelists.org/codelist/user/richard-croker/non-high-dose-long-acting-opioids-openprescribing/0013e8c8
