### ISSUE TITLE
*MEDICINE* "High risk" drugs

### ISSUE THREAD

**Issue by chrisjwood16** [opensafely/codelist-development#246]
### User Requirements
This codelist aims to identify a number of drugs which would be considered to have high risk of patient harm. This is not an exhaustive list.

There is no nationally agreed definition of what is/isn't a high risk drug. A group of 3 senior clinical pharmacists met and agreed to include the following groups:
- Disease modifying anti-rheumatic drugs (DMARDs)
- Potentially addictive medications (high dose opioids/benzodiazapines/z-drugs)
- Potentially teratogenic medications (sodium valproate/modafanil/topiramate/carbimazole/pregabalin)
- 

### Existing codelists
DMARDs - https://www.opencodelists.org/codelist/opensafely/dmards/2020-06-23/
High dose opioids - https://www.opencodelists.org/codelist/opensafely/high-dose-long-acting-opioids-openprescribing-dmd/52f27403/
Benzodiazapines - None found
Z-drugs - None found
Potentially teratogenic medications - None found

### Borderline Cases to Highlight

Codelist:

**Comment by speed-vm** [comment]
Thanks Chris

Please can the following changes be made:

**Chapter 01: Gastro-Intestinal **System**
Nil

**Chapter 02: Cardiovascular System****

_Amiodarone_

- [ ] Remove injectables, not used in primary care setting

_Anticoagulants_
Think we can afford to be sensitive with these. In the pincer work, less common vit K antagonists also included. 

- [ ] Remove coumarin (Nil usage)

- [ ] Add acenocoumarol (>16,000 items in last 12 months Sep 21 - Aug 22)

- [ ] Add phenindione (<300 items in last 12 months Sep 21 - Aug 22) - low usage, but monitoring still important and relevant (and notable expensive for those SubICBs!). 

**Chapter 04: Central Nervous System**
NIl

**Chapter 08: Malignant Disease And Immunosuppression**

- [ ] Remove injectable azathioprine not likely to be used in primary care, and not the context we want to look at in terms of routine monitoring. 

**Chapter 10: Musculoskeletal And Joint Diseases**
Nil

- [ ] To discuss @chrisjwood16 
Assume that we will then subset patients into relevant drug or drug class and then look at medication review code distribution and frequency that way rather than use individual codelists for each drug or drug class. 
One consideration is, what if a patient is on more than one high risk medication? We could report descriptively that on 2 , and then just consider separately for code usage for example.

**Comment by speed-vm** [comment]
### Disease modifying anti-rheumatic drugs (DMARDs)

Include conventional/traditional DMARDs (synthetic and targeted are not included)

A list of conventional/traditional DMARDS was previously assembled in OpenSAFELY using North Central London prescribers guide for DMARDs. Reviewed November 2022, no reason to change approach. However, do need to check for codelist rot.

[**Previous DMARD codelist**](https://www.opencodelists.org/codelist/opensafely/dmards/2020-06-23/)
[**New DMARD codelist:**](https://www.opencodelists.org/codelist/user/speed-vm/medications-dmards/4558793e/)
_Key differences with new list:_
Gold not included in new list
Preparations that indicate DMARD given as an infusion not included ('vials for infusion')

**Comment by chrisjwood16** [comment]
@speed-vm Reviewed teratogenic medicines codelist. Happy with the codelist - please can you edit metadata:

- [ ] Add 'valproic acid' to search terms
- [ ] List preperations for injection under exclusions

Happy for it to then be published in DM+D format.
