### ISSUE TITLE
*MEDICATION* Azithromycin

### ISSUE THREAD

**Issue by speed-vm** [opensafely/codelist-development#250]
**User Requirements**
In response to shortages due to strep A outbreak, a codelist for all oral preparations of azithromycin is required.

**Search Terms**

**Inclusion Criteria for Codes**

**Exclusion Criteria for Codes**

**Borderline Cases to Highlight**

**Codelist**

**Comment by a-d-brown** [comment]
It looks like we've already got this one:
https://www.opencodelists.org/codelist/opensafely/azithromycin-medication/2020-07-06/#full-list

Although perhaps it may need to be rebuilt if affected by codelist rot - we can check with Rich next week.

**Comment by a-d-brown** [comment]
As discussed, previous version is affected by codelist rot, so new version generated as below...

**User Requirements:** In response to shortages due to strep A outbreak, a codelist for all oral preparations of azithromycin is required.

**Search Terms:** azithromycin.

**Inclusion Criteria for Codes:** Any oral formulation of azithromycin.

**Exclusion Criteria for Codes:** Any non-oral formulation of azithromycin.

**Borderline Cases to Highlight:** None.

**Codelist:** https://www.opencodelists.org/codelist/user/Andrew/azithromycin-oral/69919194/#full-list

@speed-vm you can check it looks ok, then I'll add the above as metadata and reupload as dm+d.

**Comment by speed-vm** [comment]
@a-d-brown looks good to me

**Comment by speed-vm** [comment]
https://www.opencodelists.org/codelist/opensafely/azithromycin-oral/42faf594/ now published as dm+d, meta data added.
