### ISSUE TITLE
*VACCINATION* Childhood vaccination

### ISSUE THREAD

**Issue by andrewscolm** [opensafely/codelist-development#254]
### User Requirements
This codelist aims to identify patients who have had any type of childhood vaccination.

### Existing codelists
https://github.com/opensafely/vaccinations-dashboard/blob/d8823f759fddf1b0e30f6551e120b1f32a0c4890/analysis/study_definition.py#L21-L39
Uses deprecated `VaccinationsStudyDefinition()` function

### Search Terms
https://jobs.opensafely.org/datalab/opensafely-internal/tpp-vaccination-names/outputs/25/output/vaccination_names.csv

### Inclusion Criteria for Codes
Terms relating to childhood vaccinations (BCG, MMR, DTaP, etc.)

### Exclusion Criteria for Codes
NA

@opensafely/clininform

**Comment by speed-vm** [comment]
Starting to compile list: 
(Source is current Red Book version August 2021)

### Standard list

- **8 weeks** 
- [ ] Meningococcal B vaccine
- [ ] Rotavirus vaccine
- [ ] Diphtheria / Tetanus / acellular pertussis (whooping cough)/inactivated polio vaccine / _haemophilus influenzae b_ vaccine/ hepatitis B vaccine 

-**12 weeks**
- [ ] Pneumococcal conjugate vaccine
- [ ] Rotavirus vaccine
- [ ] Diphtheria / Tetanus / acellular pertussis (whooping cough)/inactivated polio vaccine / _Haemophilus influenzae b_ vaccine/ hepatitis B vaccine 

**16 weeks**
- [ ] Meningococcal B vaccine
- [ ] Rotavirus vaccine
- [ ] Diphtheria / Tetanus / acellular pertussis (whooping cough)/Inactivated polio vaccine / _Haemophilus influenzae b_  vaccine/ hepatitis B vaccine 

**One year**
- [ ] Meningococcal B vaccine
- [ ] Pneumococcal conjugate vaccine
- [ ] Meningococcal C vaccine and _Haemophilus influenzae b_ 
- [ ] Measules, Mumps, & Rubella

**Annually from two years**
- [ ] Influenza Vaccine

**Three years and four months (Pre-school immunisations)**
- [ ] Diphtheria or low dose diphtheria, tetanus, acellular pertussis (whopping cough), inactivated polio vaccine)
- [ ] Measles, Mumps & Rubella

**12 and 13 years old (school year 8)** 
- [ ] Human papillomavirus vaccine (2 doses, 6 months apart)

**14 years old (school years 9 - 10)**
- [ ] Low dose diphtheria, tetanus, inactivated polio vaccine)
- [ ] Meningococcal ACWY vaccine

### Non-standard*
* some babies may need BCG and or hepatitis B vaccine.

To be continued...

**Comment by chrisjwood16** [comment]
CSV file of vaccines with added column detailing components:
https://docs.google.com/spreadsheets/d/1lDy_FF_oqgexegvlMul16yK3Z8ZGPUyF6QF4pRkdEcc/

**Comment by chrisjwood16** [comment]
Discussed with Colm and Will.

Given study looks at up to 15 years old and complexities this brings due to changes to vaccination schedule/brands used over time - agreed reasonable to have a couple of representative vaccines rather than attempt to cover all vaccines.
Agreed for now look to include 
- DTaP/IPV/Hib or DTaP/IPV/Hib/HepB containing vaccines
- DTaP/IPV - given as booster
- MMR vaccine - vaccine with [lower uptake of primary course](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/356061/The_Immunisation_Coverage_1966_2012_13.pdf)

Tasks:
- [x] Check for national published data on vaccine update which can be used for comparison with results
Available here - https://www.gov.uk/government/collections/vaccine-uptake
- [ ] Consider how vaccine info is recorded for <16 years if moving GP - between same EHR/different EHR/countries
- [ ] Look at practicalities of catch-up programme

**Comment by chrisjwood16** [comment]
Timeline of vaccination schedules:
[UKHSA timeline of introduction to UK routine vaccination programmes](https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/1052154/UKHSA-vaccine-timeline.pdf)

[Green Book 1996](https://webarchive.nationalarchives.gov.uk/ukgwa/20060206141922mp_/http://www.dh.gov.uk/assetRoot/04/07/29/84/04072984.pdf) - for reference only (p51)

[Green Book 2006](https://webarchive.nationalarchives.gov.uk/ukgwa/20080818020739/http://www.dh.gov.uk/en/Publichealth/Healthprotection/Immunisation/Greenbook//DH_4097254) - [Chapter 11 Immunisation schedule](https://webarchive.nationalarchives.gov.uk/ukgwa/20080818020739mp_/http://www.dh.gov.uk/en/Publichealth/Healthprotection/Immunisation/Greenbook//DH_4097254?IdcService=GET_FILE&dID=115682&Rendition=Web)
[Green Book Dec 2010](https://webarchive.nationalarchives.gov.uk/ukgwa/20110321150233mp_/http://www.dh.gov.uk/prod_consum_dh/groups/dh_digitalassets/@dh/@en/documents/digitalasset/dh_123402.pdf)
[As of September 2008](https://webarchive.nationalarchives.gov.uk/ukgwa/20100303152147mp_/http://www.immunisation.nhs.uk/files/schedule_oct08.pdf)
[As of Dec 2009](https://webarchive.nationalarchives.gov.uk/ukgwa/20100303163311/http://www.hpa.org.uk/web/HPAweb&Page&HPAwebAutoListDate/Page/1204031508623)
[As of May 2010](https://webarchive.nationalarchives.gov.uk/ukgwa/20100703045005/http://www.hpa.org.uk/web/HPAweb&Page&HPAwebAutoListDate/Page/1204031508623)
[As of May 2011](https://webarchive.nationalarchives.gov.uk/ukgwa/20111108184342/http://www.hpa.org.uk/web/HPAweb&Page&HPAwebAutoListDate/Page/1204031508623)
[As of Nov 2012](https://webarchive.nationalarchives.gov.uk/ukgwa/20130502133811/http://www.hpa.org.uk/web/HPAweb&Page&HPAwebAutoListDate/Page/1204031508623)
[From June 2013](https://webarchive.nationalarchives.gov.uk/ukgwa/20131114141845mp_/https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/204061/DoH_Imm_schedule_poster_A4_2013_07_accessible.pdf)
[From Summer 2014](https://webarchive.nationalarchives.gov.uk/ukgwa/20140611161113mp_/https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/317404/8807_PHE_Complete_Immunisation_Schedule_A4_2014_10_accessible.pdf)
[From Summer 2015](https://webarchive.nationalarchives.gov.uk/ukgwa/20151204031116/https://www.gov.uk/government/publications/the-complete-routine-immunisation-schedule)
[From Spring 2016](https://webarchive.nationalarchives.gov.uk/ukgwa/20160810042940mp_/https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/523050/PHE_Complete_Immunisation_Schedule_SPRING16.pdf)
[From Summer 2016](https://webarchive.nationalarchives.gov.uk/ukgwa/20160810042938mp_/https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/532787/PHE_Complete_Immunisation_Schedule_SUMMER2016.pdf)
[From Autumn 2017](https://webarchive.nationalarchives.gov.uk/ukgwa/20170804234259mp_/https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/633693/Complete_imm_schedule_2017.pdf)
[From April 2018](https://webarchive.nationalarchives.gov.uk/ukgwa/20180411220301mp_/https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/696501/Complete_immunisation_schedule_April2018.pdf)
[From Autumn 2018](https://webarchive.nationalarchives.gov.uk/ukgwa/20190320174345mp_/https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/741543/Complete_immunisation_schedule_sept2018.pdf)
[From Autumn 2019](https://webarchive.nationalarchives.gov.uk/ukgwa/20200306150016mp_/https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/824542/PHE_complete_immunisation_schedule_autumn_2019.pdf)
[From Jan 2020](https://webarchive.nationalarchives.gov.uk/ukgwa/20200306150015mp_/https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/849184/PHE_complete_immunisation_schedule_Jan2020.pdf)
[From June 2020](https://webarchive.nationalarchives.gov.uk/ukgwa/20210401220006mp_/https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/899423/PHE_Complete_Immunisation_Schedule_Jun2020_05.pdf)
[From Feb 2022](https://webarchive.nationalarchives.gov.uk/ukgwa/20220402185121mp_/https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/1055877/UKHSA-12155-routine-complete-immunisation-schedule_Feb2022.pdf)

Using 2006 Green Book Schedule as starting point:
- DTaP/IPV/Hib in schedule pre-2006 to Autumn 2017 then replaced by DTaP/IPV/Hib/HepB
- DTaP/IPV in schedule pre-2006 onwards
- MMR in schedule pre-2006 onwards
- PCV (3 doses) in schedule pre-2006 to Jan 2020 - then reduced to 2 doses from Jan 2020 onwards
- Hib/Men C in schedule pre-2006 onwards ([note future plans to change this due to discontinuation of combined product](https://www.gov.uk/government/publications/jcvi-interim-statement-on-changes-to-the-childhood-immunisation-schedule/joint-committee-on-vaccination-and-immunisation-jcvi-interim-statement-on-the-immunisation-schedule-for-children) - although no changes to schedule to date and supplies expected to last until 2025) 
- Td/IPV in schedule pre-2006 onwards
- Men C only vaccine in schedule pre-2006 removed Summer 2016 - excluded for now

Vaccines in Feb 2022 schedule not in 2006 schedule - excluded for consistency across study period:
- Men B
- Rotavirus
- Influenza
- HPV
- Men ACWY

**Comment by chrisjwood16** [comment]
**User Requirements**
This codelist aims to identify patients who have had any of a key set of childhood vaccinations. Patients included in the study will range from 0-16 - i.e. born approx 2007 or later.

**Resources used** - see above for links
Immunisation against infectious disease - 'The Green Book' - archived versions [1996](https://webarchive.nationalarchives.gov.uk/ukgwa/20060206141922mp_/http://www.dh.gov.uk/assetRoot/04/07/29/84/04072984.pdf), [2006](https://webarchive.nationalarchives.gov.uk/ukgwa/20080818020739mp_/http://www.dh.gov.uk/en/Publichealth/Healthprotection/Immunisation/Greenbook//DH_4097254?IdcService=GET_FILE&dID=115682&Rendition=Web)
Immunisation.nhs.uk - Routine Childhood Immunisation Schedule [2008](https://webarchive.nationalarchives.gov.uk/ukgwa/20100303152147mp_/http://www.immunisation.nhs.uk/files/schedule_oct08.pdf)
Health Protection Agency - Routine Childhood Immunisation Schedule 2009, 2010, 2011, 2012
Department of Health - Routine Childhood Immunisation Schedule 2013
Public Health England - Routine Childhood Immunisation Schedule 2009, 2010, 2011

**Search Terms/Methods**
A list of vaccine names was exported using OpenSAFELY-TPP which contained a combination of generic names, brand names and also included a number of non-vaccine products e.g. immunoglobulins, monoclonal antibody products used for prevention of infectious disease (e.g. palivizumab).
A clinical informatician manually reviewed the list, categorized the products by components and filtered out non-vaccine products.

**Inclusion Criteria for Codes**
Vaccines containing any of the following combinations:
DTaP/IPV/Hib
DTaP/IPV/Hib/HepB
dTaP/IPV or DTaP/IPV
MMR 
PCV
Hib/Men C
Td/IPV

**Exclusion Criteria for Codes**
Vaccines containing some but not all of the components listed in inclusion criteria. - e.g. MMR included, 
Vaccines not listed above

**Borderline Cases to Highlight**

**Codelist**

**Comment by speed-vm** [comment]
@chrisjwood16 Just had a look through and had two comments:
1. Suggest to include the reason why the following are excluded, on the basis that DTaP/IPV and DTaP/IPV/HiV/HepC are included:
DTaP/Hib
DTaP/IPV/Hib/MenC
Or should they be included?

2. In the exclusion to also say not including the individual elements of the DTaP, or include within the Hep B example to keep concise?

**Comment by chrisjwood16** [comment]
@speed-vm I've updated the exclusions:
1. Combination vaccines with similar but non-identical components to those listed above - e.g. DTaP/Hib, DTaP/IPV/Hib/MenC
2. Single vaccines of combination vaccines listed above - e.g. Hep B vaccine given alone, Diptheria vaccine given alone
I've also added an "important notes" section

**Comment by speed-vm** [comment]
@chrisjwood16 yes, thats covered those 2 points, and the important notes are important for the correct use of the codelist, agree.

**Comment by chrisjwood16** [comment]
Discussed with @andrewscolm 
Looking to identify all patients who have received all doses of selected vaccines.
Age groups covering range 5-15.
Agreed remove Tetanus, diphtheria and polio booster (Td/IPV) as given only at 14 years old (minority of included population).
Rest of vaccines expected would be given before 5th birthday (due on or before 3years 4months) so relevant to include.
Need to account for changes occurring from Autumn 2017 - so would expect in the included group to be given EITHER DTaP/IPV/Hib OR DTaP/IPV/Hib/HepB
[selected_childhood_vaccines-updated.csv](https://github.com/opensafely/codelist-development/files/11478495/selected_childhood_vaccines-updated.csv)
