### ISSUE TITLE
*CONDITION* COVID-19 A&E diagnosis codes

### ISSUE THREAD

**Issue by alschaffer** [opensafely/codelist-development#263]
**User Requirements**
This codelist aims to identify patients who visited A&E due to COVID-19, for use as an outcome in studies (either alone or combined into a composite outcome with COVID-19 hospitalisation/COVID-19 deaths).

**Inclusion Criteria for Codes**
All SNOMED codes where the description includes the word COVID-19 in the NHS Emergency Care Data Set (ECDS) Enhanced Technical Output Specification (ETOS) v4.0 (see Worksheet 21.1 Diagnosis): https://digital.nhs.uk/data-and-information/data-collections-and-data-sets/data-sets/emergency-care-data-set-ecds/ecds-guidance. Deprecated codes were included.

**Exclusion Criteria for Codes**
N/A

**Codelist** 
https://www.opencodelists.org/codelist/user/anschaf/covid-19-ae-diagnosis-codes/1df1c0b2/

**Comment by wjchulme** [comment]
Explanatory note: the spreadsheet linked to above contains the snomed refset for "discharge diagnosis" from A&E attendances in the ECDS dataset. The diagnosis field in ECDS should therefore contain only the codes listed here. However, it's not clear if this is the canonical place to look for this refset, nor how to be alerted of updates.

**Comment by chrisjwood16** [comment]
@alschaffer
I'm happy to approve this codelist for use with ECDS data source.
I've also checked against ETOS v3.1.1 as there is a mention that implementation date for ECDS ETOS v4.0 is 1 July 2023. Codes are the same across both versions.

@wjchulme [This page](https://digital.nhs.uk/data-and-information/data-collections-and-data-sets/data-sets/emergency-care-data-set-ecds) seems to suggest the ETOS is the recommended source:
"Updates to reference sets
Due to the ECDS Technical Committee approved change release schedule differing from the SNOMED release schedule (TRUD). Providers and suppliers should use the published ECDS Enhanced Technical Output Specification, aligned with the SUS+ submission portal approved codes list for implementing all changes, rather than TRUD to avoid submission and Data Quality issues seen previously."

**Comment by alschaffer** [comment]
Thanks @chrisjwood16. I've made a few modifications to the metadata to include some of this information. Just checking what needs to happen next? Does someone need to sign off? Do we need another review?

**Comment by wjchulme** [comment]
Also checked the codelist and happy with this
