### ISSUE TITLE
*MEDICINE* Long-acting insulin

### ISSUE THREAD

**Issue by a-d-brown** [opensafely/codelist-development#270]
**User Requirements**
Identify patients who are taking a long-acting insulin. This will be used alongside a GLP-1 codelist to identify a specific cohort of patients and assess the impact of the impact of GLP-1s being prescribed for weight loss.

**Search Terms**
- Insulin

**Inclusion Criteria for Codes**
- Refers to a long-acting insulin with no other medicines in combination.

**Exclusion Criteria for Codes**
- Refers to a short-acting, intermediate acting, or biphasic insulin.
- Refers to a long-acting insulin in combination with another medicine, e.g. GLP-1.
- Refers to a non-insulin product.
- Products discontinued in the UK, e.g. protamine zinc insulin, insulin zinc suspension.

**Borderline Cases to Highlight**
- None

**Codelist**
https://www.opencodelists.org/codelist/user/Andrew/insulin-long-acting-basal/646512fd/

**Comment by chrisjwood16** [comment]
BNF defines long-acting insulins - https://bnf.nice.org.uk/treatment-summaries/insulin/
Their definition includes Protamine zinc insulin (0601012U0), Insulin zinc suspension (0601012G0)/Insulin zinc suspension (Crystalline) (0601012N0)  so could include those for completeness. But also note seem to be discontinued in UK and no prescriptions since 2019 so could equally exclude on that basis.

For long-acting insulin in combo with GLP-1 - will this be a separate codelist (or included in GLP-1 codelist)?

**Comment by a-d-brown** [comment]
Thanks Chris, yeah I spent a while sifting through all the zinc cases (sorry perhaps should have mentioned in notes). As far as I could tell all the relevant cases had been discontinued.

Yes, a separate codelist is being developed specifically to identify the products which are a combination of long-acting insulin with a GLP-1.

**Comment by chrisjwood16** [comment]
Great.
Please just add "insulin products discontinued in the UK (protamine zinc insulin, insulin zinc suspension)" to the exclusions above and I'm happy to approve.

**Comment by a-d-brown** [comment]
Added, thanks. Here is the dm+d version for completeness:
https://www.opencodelists.org/codelist/user/Andrew/insulin-long-acting-basal-dmd/02da061f/#full-list
