### ISSUE TITLE
*Disease* Valvular atrial fibrillation

### ISSUE THREAD

**Issue by angelwong121** [opensafely/codelist-development#40]
Rationale of developing the codelist:
This is used for the anticoagulant use before COVID project. We will exclude people with atrial fibrillation (valvular in nature) in analysis of comparing warfarin and DOAC users because DOAC is not indicated for valvular atrial fibrillation.

URL of codelist builder: https://codelists.opensafely.org/builder/angel-wong/valvular-atrial-fibrillation/

Coding system: SNOMED CT

Search terms are based on a published paper (Table 4): https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6130300/pdf/clep-10-1155.pdf

Keyword searched in codelist builder: 
```
aortic valve implantation
artificial heart valve
disease of mitral and aortic valve
heart valve prosthesis
heart valve replacement
mitral and aortic
mitral and tricuspid
mitral stenosis
mitral valve disease
mitral valve disorder
mitral valve stenosis
mitral valvotomy
mitral valvuloplasty
multiple valve
prosthetic heart valve
repair of mitral valve
replacement of mitral valve
replacement of aortic valve
replacement of truncal valve
```

Before generating the codelist here, I excluded codes only indicating physical object, e.g. cardiac valve prosthesis, device (not the procedure itself), cine study of artificial heart valve, Computed tomography angiography planning or the specimen of heart valve.

The codelist for review:
[angel-wong-valvular-atrial-fibrillation-2020-11-09T19-00-08.xlsx](https://github.com/opensafely/codelist-development/files/5516985/angel-wong-valvular-atrial-fibrillation-2020-11-09T19-00-08.xlsx)

**Comment by laurietomlinson** [comment]
[angel-wong-valvular-atrial-fibrillation-2020-11-09T19-00-08_LT.xlsx](https://github.com/opensafely/codelist-development/files/5652661/angel-wong-valvular-atrial-fibrillation-2020-11-09T19-00-08_LT.xlsx)

Rather than valvular AF yes/no I have created sub columns that you can combine as you like
1.	Valve replacement
2.	Mentions tissue/prosthetic valve (these may not be anticoagulated)
3.	Mitral stenosis
4.	Mitral regurgitation (unlikely to be anticoagulated unless another issue)
5.	Unclear mitral valve lesion (not specific to stenosis or regurgitation: this is the tricky one – depends on whether you want to be sensitive or specific)
6.	Other valve lesion (not relevant here)


Assumptions – if someone has had a procedure to open a mitral valve I have assumed they had and still have mitral stenosis
I have assumed papillary muscle rupture leads to mitral regurgitation but not if there is a repair as this could in theory lead to the need to be anticoagulated)

**Comment by angelwong121** [comment]
thanks @laurietomlinson 
As our codelist is developed for identifying people who had contraindication of DOACs for exclusion, we can keep the codes for artificial valves and mitral stenosis.
The codelist ready to be converted to CTV3: 
[angel-wong-valvular-atrial-fibrillation-2020-11-09T19-00-08_LT_AW.xlsx](https://github.com/opensafely/codelist-development/files/5653272/angel-wong-valvular-atrial-fibrillation-2020-11-09T19-00-08_LT_AW.xlsx)

**Comment by angelwong121** [comment]
@laurietomlinson
the codelist has converted to CTV3: 
[angel-wong-valvular-atrial-fibrillation-2020-11-09T19-00-08_LT_AW-ctv3.xlsx](https://github.com/opensafely/codelist-development/files/5658984/angel-wong-valvular-atrial-fibrillation-2020-11-09T19-00-08_LT_AW-ctv3.xlsx)
I had a quick look and there seems no big issues after the conversion. It would be great if you can have a quick look. If you are happy with this, can you help sign it off too?

POTENTIAL BIASES / NOTE: We only included codes for artificial valves and mitral stenosis.

CLINICAL SIGN OFF & DATE: 

EPIDEMIOLOGY SIGN OFF & DATE: Angel Wong @angelwong121 8/12/2020 11:36

SHARED WITH WIDER TEAM: Yes

FINAL SIGN OFF DATE (and apply label):

**Comment by angelwong121** [comment]
Due to the formatting issue from excel - re-reviewed the codes after converting to ctv3
Attached the final version:
[angel-wong-valvular-atrial-fibrillation-6c4ca3b9_AW-ctv3.csv.txt](https://github.com/opensafely/codelist-development/files/5702284/angel-wong-valvular-atrial-fibrillation-6c4ca3b9_AW-ctv3.csv.txt)
