### ISSUE TITLE
*Medicines* hormone replacement therapy/contraceptives

### ISSUE THREAD

**Issue by angelwong121** [opensafely/codelist-development#43]
Rationale of developing the codelist:
This is used for the anticoagulant use before COVID project. We will identify people prescribed hormone replacement therapy/ contraceptives as covariate to be adjusted for. Because HRT/contraceptive increases the risk of venous thromboembolism.

URL of codelist builder: https://codelists.opensafely.org/builder/4c4a497a/search/estradiol/
Coding system: pseudo BNF

Keyword searched in codelist builder:
```
estradiol
estriol
estrone
ethinylestradiol
medroxyprogesterone
mestranol
norethisterone
oestrogen
raloxifene
tibolone
```

Before generating the codelist here, I excluded codes indicating vaginal cream/devices and nasal spray. I also excluded BNF 0605 chapter `Hypothalamic and pituitary hormones and anti, oestrogens`. Please note that some medicines belong to BNF 08 chapter `Malignant Disease and Immunosuppression`, because they can also be used as contraceptives which can increase risk of thrombotic events so they were included in this version.

The codelist for review:
[angel-wong-hrtcontraceptive-4c4a497a.xlsx](https://github.com/opensafely/codelist-development/files/5643055/angel-wong-hrtcontraceptive-4c4a497a.xlsx)

**Comment by brianmackenna** [comment]
I won't get to checking this list this week, my focus is on recruiting new folk to help us with codelists. One observation I would make is I think it makes sense to do contraception and HRT as separate codelists. The main advantage being that they would be more reusable across a wider range of studies.

**Comment by hammoire** [comment]
Code list clinical logic.

Where evidence is strong we have followed this, but where evidence is lacking or ambiguous we have taken a 'biologically plausibility' approach. For example, some evidence suggests that transdermal HRT is not associated with an increased risk of VTE due to bypassing first pass hepatic metabolism. However, as oral systemic estrogens are strongly associated with an increased risk of VTE we have elected to include transdermal estrogens. This logic has been followed throughout. Although it could be reasonably argued to take the opposite approach. The main downside to the opposite approach is that using weaker evidence to make decisions. 


**HRT:** 
- Good evidence to include all oral estrogen based HRT with and with without progesterone. 
- The evidence for transdermal  HRT and VTE is weaker but it is still a systemic estrogen and so it is still biologically plausible that it could increase risk of VTE and therefore included. As mentioned in a previous study a sensitivity analysis with and without transdermal estrogens could be an option. 
- Topical vaginal estrogen not included as they are not 'systemic' estrogens and therefore risk could be expected to be lower furthermore not strong positive evidence of association with VTE. 

**Contraception**
- Good evidence to include all oral estrogen containing oral contraceptives. 
- Include estrogen and progesterone contraceptive patch following the same logical as HRT
- Exclude estrogen and progesterone ring following same logic as HRT.
- Exclude any progesterone only medication as evidence suggests a lack of association with VTE. Injectable progesterone contraception has some evidence of VTE association, but given we are taking a 'biologically plausibility' approach with HRT, for methodological consistency exclude injectable progesterone contraceptive as well. 

**Specific**
- Exclude tibalone as limited evidence of an association with VTE.
- Include raloxifene as evidence of increased risk VTE and therefore seems reasonable to include other biologically similar drugs:  tamoxifen, ospemifene, Toremifene.
- Include oral diethylstilbestrol as is systemic synthetic estrogen.

**Comment by angelwong121** [comment]
Thanks @hammoire 
According to this logic, we excluded search terms: 
```
medroxyprogesterone
norethisterone
tibolone
```
And additionally included search terms:
```
tamoxifen
ospemifene
toremifene
```
The latest codelist for review:
https://codelists.opensafely.org/codelist/user/angel-wong/hrtcontraceptive/2c47ef3b/#full-list
@hammoire  can you double check this and please sign this off if you are happy with this version:

POTENTIAL BIASES / NOTE: We included codes for oral form and patches and excluded vaginal cream/devices and nasal spray.

CLINICAL SIGN OFF & DATE: 

EPIDEMIOLOGY SIGN OFF & DATE: Angel Wong @angelwong121 22/12/2020 16:03

SHARED WITH WIDER TEAM: Yes

FINAL SIGN OFF DATE (and apply label):

**Comment by hammoire** [comment]
@angelwong121 I still see Tibolone under the Oestrogen search term. Other than that I think it's good to go

Tibolone (0604011Y0)
Tibolone (0604011Y0AA)
Tibolone 2.5mg tablets (0604011Y0AAAAAA)

**Comment by angelwong121** [comment]
Well spot! thanks @hammoire 
Revised version: https://codelists.opensafely.org/codelist/user/angel-wong/hrtcontraceptive/7a2908d0/#full-list

POTENTIAL BIASES / NOTE: We included codes for oral form and patches and excluded vaginal cream/devices and nasal spray.

CLINICAL SIGN OFF & DATE:

EPIDEMIOLOGY SIGN OFF & DATE: Angel Wong @angelwong121 22/12/2020 16:28

SHARED WITH WIDER TEAM: Yes

FINAL SIGN OFF DATE (and apply label):

**Comment by hammoire** [comment]
> Well spot! thanks @hammoire
> Revised version: https://codelists.opensafely.org/codelist/user/angel-wong/hrtcontraceptive/7a2908d0/#full-list
> 
> POTENTIAL BIASES / NOTE: We included codes for oral form and patches and excluded vaginal cream/devices and nasal spray.
> 
> CLINICAL SIGN OFF & DATE: William Elson @hammoire 22/12/2020 16:29
> 
> EPIDEMIOLOGY SIGN OFF & DATE: Angel Wong @angelwong121 22/12/2020 16:28
> 
> SHARED WITH WIDER TEAM: Yes
> 
> FINAL SIGN OFF DATE (and apply label):
