### ISSUE TITLE
*DISEASE* Dementia 

### ISSUE THREAD

**Issue by annaschultze** [opensafely/codelist-development#61]
The existing code list for dementia captures only vascular dementia/a subset of codes contributing to a broader category of neurological conditions. This issue is created to develop an up to date and comprehensive code list for dementia (incl. Alzheimer's disease)

**Comment by annaschultze** [comment]
Current Dementia Code List from LSHTM EHR group (Charlotte Warren Gash), currently in medcode format. @CarolineMorton is there a way to translate this to CTV3 still or should we try and re-develop whilst cross-comparing to ensure similar terms are included? 

[dementia_codes.xlsx](https://github.com/opensafely/codelist-development/files/5880633/dementia_codes.xlsx)

**Comment by annaschultze** [comment]
@CarolineMorton - draft to review clinically is here: https://codelists.opensafely.org/builder/7c73ba80/?filter=included. This has 250 (!) terms, but I think it should be reasonably quick to review. 

I had the following questions: 

- Should we include or exclude "Exception reporting: dementia quality indicators"? I've currently excluded but wasn't entirely sure what they meant. I've included other administrative codes, apart from screening. 
- On the GDS assessment scale, I've excluded those with no cognitive decline but included those level 2 or above (very mild and above). I wasn't sure if this made clinical sense 
- On administrative code, I've included care plan reviews as that sounded like something you'd do for someone with dementia, but not "advance care plans" as that sounded like something you'd do for someone about to get dementia. Can you confirm from a coding perspective? 
- the existing codelist included cerebral degeneration due to [a lot of different causes]. I wasn't sure if these were all relevant. 
- the existing codelists includes variant creutzfeld jakob disease; to confirm appropriate (it's going to be so rare I assume not enough to make a difference) 
- existing code list included huntington's chorea, but I don't think that's appropriate. I've included dementia in huntington's disease only. 

To make the codelist even more inclusive, I then went here: https://dementiapartnerships.com/resource/dementia-read-codes/ and looked for additional search terms. This added one "delirium" related code, which I'd appreciate input on whether this is relevant. 

If you could list out here the changes you're requesting for reference, then I can update and save this for implementation.

**Comment by CarolineMorton** [comment]
Hi @annaschultze 

Thanks for putting this together. I think it would be useful to have another clinical person involved as well. Perhaps @hmcd could help as well?

I am not entirely sure about `Exception reporting: dementia quality indicators` but I suspect that this represents when patients have not had a scheduled dementia review for example if they are palliative or it is inappropriate for whatever reason like they are inpatients. This would be worth checking with @amirmehrkar  as well. These patients are likely to have dementia so should probably be included. 

Re the GDS assessment, I would exclude these patients as there are a large number of patients who have some mild cognitive impairment who do not progress to dementia. For me dementia is a clinical diagnosis usually in a memory clinic and involves more involved testing including a MRI Head and some formalised testing. We don't want to include people with mild cognitive decline as they are a different population. 

I would again exclude `care plan reviews` and `advanced care plans`. These are people who have severe chronic disease, which may or may not include dementia, so there would be a risk of over ascertainment. For example, care plan reviews may be someone with a learning difficulty and heart failure. Advanced care plans tend to be for people who you would not be surprised if they passed away in the next year or so, so again this is not dementia specific. 

`creutzfeld jakob disease` seems reasonable to include. 
`Cerebral degeneration` and `cerebral atrophy` appear to be too non-specific. It might just be noted on a scan. 
`Seen by Parkinson's disease service` should be excluded as should the referral to clinical nurse specialist for PD. 
There are a lot of Parkinson's Disease codes included. I think these should be excluded unless there is specific mention of dementia. 

Delirium is a transcient acute confusion and does not represent Dementia (although lots of dementia patients can become acute delirious so it gets a bit confusing).

**Comment by brianmackenna** [comment]
Myself and @richiecroker  started investigating this independently just now - good documentation! Saved us a job!

As dementia is included in the QOF we should also make a mirror of the QOF register using the business rules [refset for dementia](https://termbrowser.nhs.uk/?perspective=full&conceptId1=999002771000000107&edition=uk-edition&release=v20210120&server=https://termbrowser.nhs.uk/sct-browser-api/snomed&langRefset=999001261000000100,999000691000001104). As we are imminently making snomed available in TPP  it makes sense to prioritise import all QOF business rules refsets I think @inglesp

**Comment by brianmackenna** [comment]
As regards current dementia list is is currently in use in the following studies

https://github.com/search?q=org%3Aopensafely+codelist%2Fopensafely%2Fdementia%2F2020-04-22&type=code

@HelenCEBM @wjchulme @rohinimathur @kevwing @dgrint appear to be using and will want to follow outcome of this discussion I think. (for morning meeting to resolve it quickly).

**Comment by richiecroker** [comment]
Business rules for QOF can be found [here](https://digital.nhs.uk/data-and-information/data-collections-and-data-sets/data-collections/quality-and-outcomes-framework-qof)

**Comment by helenmcd** [comment]
Thanks for developing this @annaschultze it looks really thorough! 

Have started looking at it - would need to go through the clinical findings section in a bit more detail to finish, but some quick thoughts:

On the Exception reporting codes, I would also include these as they should be people who have dementia but for whom the QOF indicators are not appropriate (e.g. people who do not attend reviews). To be exception reported they will also already be on the dementia register though, so if this list includes all diagnoses in the QOF register then including the exception reporting codes shouldn’t make a difference to ascertainment.

I agree on excluding GDS assessments, care plan reviews and advanced care plans, Seen by Parkinson's disease service, and referral to clinical nurse specialist for PD.

In the admin codes, I would also exclude Referral to dementia service(XaZqJ) and Referral for dementia assessment(XabuR) since they may be being referred to assessment, but this doesn’t yet confirm the diagnosis.

I’m not sure, but I would be inclined to exclude Referral to dementia support organisation(Xabd3) and Signposting to dementia support service(XagMZ) Referral to dementia support organisation declined(Xabd2) as these could be relevant for carers.

I agree with @CarolineMorton on excluding Parkinson's disease codes unless they record dementia.

On drugs, I wonder whether it might be worth keeping that for a separate list? Depending on what study the variable is being used for, it may or may not be a problem for ascertainment bias if more likely to identify people as having dementia if they are receiving medication for it. If we're using CTV3 codes for it, would also like to look at the medications records too.

**Comment by annaschultze** [comment]
Thanks all! @helenmcd @CarolineMorton I've excluded the codes you noted, unless there were specific mentions of dementia (relevant for parkinson's and delirium). I added exception reporting codes back in. I agree with Helen that we should keep drugs for a separate list, and have excluded CTV3 codes for drugs. 

@brianmackenna @richiecroker sorry for asking again - please bear with me as I'm relatively new to some of these UK standards - but what exact codes do you want me to add if any? I couldn't find a list anywhere on the links you sent through. 

If there is a separate dementia code list that's more narrow I think perhaps worth adding this as a separate list, and we can cross compare. I don't think there's harm in having this added as a comprehensive list of all codes we think are relevant, but if anyone disagrees please shout..!

**Comment by annaschultze** [comment]
Decision: QOF lists will be implemented separately, and this code list will be published as is as a comprehensive list of dementia codes.

**Comment by annaschultze** [comment]
@CarolineMorton @HelenCEBM I'm working through the process of publishing this with Peter. Would you be willing to provide clinical and epi sign off on the list as below? It'd be useful to have this signed off for use as a few projcts are looking to use the list. Please let me know in case of any proposed changes, or if further review is needed and I'll see if Amir might have time to also look over. 

**SIGN OFF** 

SUMMARY: This code list captures Dementia and Alzheimer’s disease. It is intended to be inclusive. 

**Inclusion Criteria:**

- All clinical findings containing a mention of Dementia 
- Dementia monitoring, reviews and exception reporting 
- All clinical findings containing a mention of Alzheimer’s disease
- Senile and presenile organic psychotic conditions
- Other:  
    - Progressive multifocal leucoencephalopathy
    -Creutzfeldt-Jakob disease 
    -Reye's syndrome
    - Organic hallucinosis
    - Chronic alcoholic brain syndrome
    - Extrapyramid dis: [excl Parkinson][oth and abn movem disord]

**Exclusion Criteria:**
- Cerebral or Brain degeneration without mention of dementia 
- Drugs used to treat Dementia 
- Dementia Care Plan 
- Dementia/Alzheimer Referrals 
- Tests for dementia/alzheimer's
- Delerium (without mention of dementia) 

CLINICAL SIGN OFF & DATE:
EPIDEMIOLOGY SIGN OFF & DATE:
FINAL SIGN OFF DATE (and apply label)

**Comment by helenmcd** [comment]
Hi @annaschultze thanks, and I agree it's useful to have this list separate to QOF

(1) I would suggest removing 
- Assessment: [mental disability] or [memory] or [dementia](3A...)
as this is a bit broad and also an assessment which could be to see whether they have memory loss etc
- [X]Child disinteg dis:[oth][dement infantalis (& named var)](Eu843) - I think this is a pervasive development disorder rather than dementia, I wouldn't include it
- Reye's syndrome(F11y0). This can cause liver and brain damage, but doesn't necessarily cause brain damage, I wouldn't include it
- I don't think Charles Bonnet syndrome(F49z0) constitutes dementia. https://rarediseases.info.nih.gov/diseases/10343/charles-bonnet-syndrome

(2) I also wouldn't include Progressive multifocal leucoencephalopathy(A413.) 
BUT I would add in
F11x8 Cerebral degeneration due to multifocal leucoencephalopathy

(3) There are a few I'm not sure about clinically, and I think it'd be good to check these with a practising clinician. Perhaps @CarolineMorton or Amir might review these? 

a) Drug-induced dementia(E02y1) - I had to search to check if it's permanent - it looks to be, but would be good to check with someone who is familiar with it
b) (Child cerebr degen) or (hydroceph) or (senile brain degen)(XE17h) - this is very broad. The first two wouldn't make it into the list. I'm not sure how this code would be used, but it might over-ascertain
c) Cerebral degeneration in Parkinson's disease (XaOfZ) - seems most likely to imply dementia - could it be the finding from a brain scan of someone with Parkinson's disease and how likely is that if so? 
d) I wasn't sure whether Organic hallucinosis(E03y1) is classified within dementia or is a separate concept, but it's in the dementia partnerships read codelist as dementia, so I'd include it unless you get advice otherwise
e) [X](Ment/beh dis due alc, resid/late) or (chr alc brain syn)(Eu107) - I wondered whether this might be too broad if it captures mental and behavioural disorders due to alcohol - I think that could include alcohol dependence or acute intoxication? https://www.who.int/substance_abuse/terminology/ICD10ResearchDiagnosis.pdf

**Comment by annaschultze** [comment]
Hi Helen, 

Thank you so much for this detailed review. I've excluded the ones you suggested and updated the inclusion/exclusion criteria below. Draft here: https://codelists.opensafely.org/builder/4c40e07d/

The codes you were unsure about I've changed to 'unresolved' in the list, could @CarolineMorton or @amirmehrkar perhaps advice on these? For code c - cerebral degeneration in Parkisons's disease, this was included as it's a subcode of cerebral degeneration, but I agree it seems more specific. Let's have one of the clinicians confirm..! It's not in the 'unresolved list' as there was no option to do so the way the builder is set up, so @CarolineMorton or @amirmehrkar please confirm here instead. Updated sign off below. Holding up updating the rest of the sign off until this is resolved. 

**Inclusion Criteria:**

- All clinical findings containing a mention of Dementia
- Dementia monitoring, reviews and exception reporting
- All clinical findings containing a mention of Alzheimer’s disease
- Senile and presenile organic psychotic conditions
- Other:
    - Cerebral Degeneration - With Dementia, due to Progressive multifocal leucoencephalopathy or due to Parkinson's (**CONFIRM IF APPROPRIATE**) 
    - Creutzfeldt-Jakob disease
    - Organic hallucinosis(**CONFIRM IF APPROPRIATE**) 
    - Chronic alcoholic brain syndrome (**CONFIRM IF TOO BROAD**) 

**Exclusion Criteria:**

- Cerebral or Brain degeneration, unless there is mention of dementia, or its due to progressive multifocal leucoencephalopathy or parkinsons disease (**CONFIRM IF EXCEPTIONS APPROPRIATE**) 
- Drugs used to treat Dementia
- Dementia Care Plan
- Dementia/Alzheimer Referrals
- Tests or assessments for dementia/alzheimer's
- Delerium (without mention of dementia)
- Development disorders 
- Reye's syndrome
- Charles Bonnet syndrome

**Comment by CarolineMorton** [comment]
Hi both, 

Thanks for this. Just going through the list and the items you have highlighted @hmcd

**Inclusion Criteria:**
Cerebral Degeneration - With Dementia, due to Progressive multifocal leucoencephalopathy or due to Parkinson's (CONFIRM IF APPROPRIATE) - **Agree that this should only be included if specifically mentions dementia as hard to know exactly how this code is being applied clinically. I suspect small numbers anyway.**
Organic hallucinosis - **not appropriate as can be temporary** 
Chronic alcoholic brain syndrome - **i think this is too broad and should be excluded. This may include Wernicke's Encephalitis (although again not clear). Might be better to specifically search for alcohol related dementia or korsakoff syndrome.** 

**Exclusion Criteria:**

Cerebral or Brain degeneration, unless there is mention of dementia, or its due to progressive multifocal leucoencephalopathy or parkinsons disease **I think I would make it so that only included if mentions dementia.**


With regard to the list here: https://codelists.opensafely.org/codelist/user/anna-schultze/dementia-complete/7c73ba80/#tree @annaschultze, the above exclusions should be applied. I would be interested to understand how Reye's Syndrome ended up in the list. Presumably this was related to a parent code. This code `Cerebr degen NOS &/or Alzh dis &/or Pick dis &/or Reye syndr` should be excluded i think due to its inclusion. 

I think it would also be appropriate to exclude `suspected dementia`. I'm on the fence about this to be honest. Is it included in the original Read 2 codelist? I think we want to capture those with confirmed dementia only and with that in mind, i think the `suspected dementia` code be exlcuded.

**Comment by annaschultze** [comment]
Hi, 

Thanks both! I've ecxluded those additional codes. `Reye's Syndrome` was included in the original Read 2 codelist, as was `suspected dementia`, but happy to follow clinical judgement and exclude these. 

Updated list here https://codelists.opensafely.org/codelist/user/anna-schultze/dementia-complete/4c40e07d/#definition, and sign off below for you to confirm. 

**Inclusion Criteria**:

- All clinical findings containing a mention of Dementia
- Dementia monitoring, reviews and exception reporting
- All clinical findings containing a mention of Alzheimer’s disease
- Senile and presenile organic psychotic conditions
- Other:
    - Cerebral Degeneration - With Dementia, due to Progressive multifocal leucoencephalopathy or due to Parkinson's 
    - Creutzfeldt-Jakob disease
    - Korsakoff/Korsakov psychosis 

**Exclusion Criteria**:

- Cerebral or Brain degeneration, unless there is mention of dementia, or its due to progressive multifocal leucoencephalopathy - or parkinsons disease (CONFIRM IF EXCEPTIONS APPROPRIATE)
- Drugs used to treat Dementia
- Dementia Care Plan
- Dementia/Alzheimer Referrals
- Tests or assessments for dementia/alzheimer's
- Delerium (without mention of dementia)
- Development disorders
- Reye's syndrome
- Charles Bonnet syndrome
- Organic hallucinosis
- Chronic alcoholic brain syndrome 
- Suspected Dementia 

CLINICAL SIGN OFF & DATE:
EPIDEMIOLOGY SIGN OFF & DATE:
FINAL SIGN OFF DATE (and apply label)

**Comment by helenmcd** [comment]
I can't work out how to edit the post above, so copied...

> Hi,
> 
> Thanks both! I've ecxluded those additional codes. `Reye's Syndrome` was included in the original Read 2 codelist, as was `suspected dementia`, but happy to follow clinical judgement and exclude these.
> 
> Updated list here https://codelists.opensafely.org/codelist/user/anna-schultze/dementia-complete/4c40e07d/#definition, and sign off below for you to confirm.
> 
> **Inclusion Criteria**:
> 
> * All clinical findings containing a mention of Dementia
> * Dementia monitoring, reviews and exception reporting
> * All clinical findings containing a mention of Alzheimer’s disease
> * Senile and presenile organic psychotic conditions
> * Other:
>   
>   * Cerebral Degeneration - With Dementia, due to Progressive multifocal leucoencephalopathy or due to Parkinson's
>   * Creutzfeldt-Jakob disease
>   * Korsakoff/Korsakov psychosis
> 
> **Exclusion Criteria**:
> 
> * Cerebral or Brain degeneration, unless there is mention of dementia, or its due to progressive multifocal leucoencephalopathy - or parkinsons disease
> * Drugs used to treat Dementia
> * Dementia Care Plan
> * Dementia/Alzheimer Referrals
> * Tests or assessments for dementia/alzheimer's
> * Delerium (without mention of dementia)
> * Development disorders
> * Reye's syndrome
> * Charles Bonnet syndrome
> * Organic hallucinosis
> * Chronic alcoholic brain syndrome
> * Suspected Dementia
> * Limbic Encephalitis
> * Progressive aphasia and Non-Alzheimer's progressive dysphasia
> * Familial fatal insomnia
> 
> CLINICAL SIGN OFF & DATE: Caroline Morton @CarolineMorton 9th Feb 2021
> EPIDEMIOLOGY SIGN OFF & DATE: Helen McDonald @helenmcd 9th Feb 2021
> FINAL SIGN OFF DATE (and apply label)
