### ISSUE TITLE
End of life / palliative Medication

### ISSUE THREAD

**Issue by brianmackenna** [opensafely/codelist-development#98]
We want to develop a list of medications that are likely to be prescribed / supplied in the last days of life. Using guidance [Community Palliative, End of Life and Bereavement Care in the COVID-19 pandemic](https://elearning.rcgp.org.uk/pluginfile.php/149457/mod_page/content/45/COVID%20Community%20symptom%20control%20and%20end%20of%20life%20care%20for%20General%20Practice%20-%20Word%20FINAL%20v3.pdf?time=1589368447206) I have made the following table of medicines that could be included. One slight issue is that some of these medicines can be used in other things (simpole linctus, morphine). I think there might be a few options on how to do this. Two that come to mind
- look for a subsection (e.g. midazolam)
- Assert that they must have a minimum of 2or3 of this medicines issued on the same day

| Ingredient                                                     | Include all preparations | Comment   |
|----------------------------------------------------------------|--------------------------|---|
| Simple linctus (PO)                                            |                          |   |
| Midazolam (SC) 2mg/2ml; 10mg/2ml; 50mg/50ml                    |                          |   |
| Dexamethasone                                                  |                          |   |
| Haloperidol (po and inj)                                       |                          |   |
| Levomopromazine                                                |                          |   |
| Metoclopramide (IV) All strengths and presentations            |                          |   |
| Prochlorperazine (PO & buccal) All strengths and presentations |                          |   |
|         Morphine                                                       |                          |   |
|         DiaMorphine                                                       |                          | Traditionally use but not recommended in guide   |

One limitation is that not all palliative care medicines are issued by GPs. For example a local hospice may have an outreach team or doctor on call might issue the prescription.

**Comment by wjchulme** [comment]
> Assert that they must have a minimum of 2or3 of this medicines issued on the same day

This isn't going to be possible to define inside a study definitition. Not easily anyway, since we can only extract first or last date in the period. For example the date of first prescription of drug A might not match the first prescription of drub B, even though they were both prescribed together on a later date. 

There might be a case to add `patients.with_these_concurrent_events()` / `patients.with_these_concurrent_medications()` type functions that looks for co-occurrence of events / prescripitions the same day. Thoughts @evansd?

> One limitation is that not all palliative care medicines are issued by GPs. For example a local hospice may have an outreach team or doctor on call might issue the prescription.

I don't think there's much we can do about this. The accompanying "end-of-life" CTV3 codelist will be more closely aligned with "death expected < 1 year" rather than "< 1 month/week" which I guess matches patients being managed in primary care more than secondary. So at least perhaps there's some consistency there?

**Comment by richiecroker** [comment]
There's also oxycodone injections to consider, sometimes used as alternative to morphine/diamorph during shortages.

I think we could use parenteral midazolam as a marker for end of life care - it doesn't have much else in the way of indications in primary care

**Comment by wjchulme** [comment]
Thanks for the work on the midazolam codelist. Going to close this issue for now and we can always reopen if we are better able to identify concurrent events in future
